FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "page:app", "--host", "0.0.0.0", "--port", "8000"]

EXPOSE 8000